# Generated by Django 5.1.3 on 2024-12-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0002_alter_leetcode_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forignlanguages',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ForeignLanguages', to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='flexapp.student'),
        ),
    ]
