# Generated by Django 5.1.1 on 2024-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0003_alter_forignlanguages_rollno_alter_projects_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='default_section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='default_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
