# Generated by Django 5.0.6 on 2025-02-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0004_projects_year_and_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='githublink',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='flexapp.faculty'),
        ),
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('certification_date', models.DateField()),
                ('certification_type', models.CharField(max_length=50)),
                ('certification_link', models.URLField()),
                ('certification_area', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='flexapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('publication_type', models.CharField(max_length=50)),
                ('publication_link', models.URLField()),
                ('publication_area', models.CharField(max_length=50)),
                ('publication_volume', models.CharField(max_length=50)),
                ('publication_notes', models.TextField()),
                ('publication_status', models.CharField(max_length=50)),
                ('publication_journal', models.CharField(max_length=100)),
                ('publication_abstract', models.TextField()),
                ('publication_keywords', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='flexapp.faculty')),
            ],
        ),
    ]
