# Generated by Django 5.1.1 on 2025-05-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0008_remove_student_github_link_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForignLanguages',
            new_name='Certificate',
        ),
    ]
