# Generated by Django 5.0.2 on 2024-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0002_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Initialized', 'Initialized'), ('In_progress', 'In Progress'), ('completed', 'Completed')], default='Initialized', max_length=255),
        ),
    ]
