# Generated by Django 5.0.2 on 2024-08-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0002_forignlanguages_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcode',
            name='easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leetcode',
            name='medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CAI', 'CAI'), ('CSD', 'CSD'), ('CSM', 'CSM'), ('CSC', 'CSC'), ('CST', 'CST'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=10),
        ),
    ]
