# Generated by Django 4.2.11 on 2024-09-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('flexapp', '0004_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forignlanguages',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='leetcode',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='studentGroups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(related_name='studentPermissions', to='auth.permission'),
        ),
    ]
