# Generated by Django 5.1.1 on 2024-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0004_faculty_default_section_faculty_default_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
