# Generated by Django 5.1.1 on 2025-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0003_forignlanguages_year_and_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='year_and_sem',
            field=models.CharField(choices=[('I-I', 'I-I'), ('I-II', 'I-II'), ('II-I', 'II-I'), ('II-II', 'II-II'), ('III-I', 'III-I'), ('III-II', 'III-II'), ('IV-I', 'IV-I'), ('IV-II', 'IV-II')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
