# Generated by Django 5.1.3 on 2025-03-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0006_filloutform_filloutfield_filloutresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='rollno',
        ),
        migrations.AddField(
            model_name='projects',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Initialized', 'Initialized'), ('In_progress', 'In Progress'), ('Completed', 'Completed')], default='Initialized', max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='flexapp.technology'),
        ),
    ]
