# Generated by Django 5.1.1 on 2025-05-11 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0009_rename_forignlanguages_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='publication_abstract',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication_journal',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication_keywords',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication_link',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication_notes',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='publication_volume',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='event_type',
            field=models.CharField(choices=[('hackathon', 'Hackathon'), ('quiz', 'Quiz'), ('workshop', 'Workshop/Webinar'), ('techfest', 'Tech Fest'), ('presentation', 'Presentation'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='fest_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recognition',
            field=models.CharField(blank=True, choices=[('participation', 'Participation'), ('appreciation', 'Appreciation'), ('recommendation', 'Recommendation')], max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='flexapp.technology'),
        ),
        migrations.AddField(
            model_name='publications',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='granted_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publications',
            name='journal_or_publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publications',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publications',
            name='volume_or_edition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('foreign_language', 'Foreign Language'), ('co_curricular', 'Co-Curricular'), ('extra_curricular', 'Extra-Curricular')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='flexapp.student'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publication_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publication_status',
            field=models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('granted', 'Granted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='publications',
            name='publication_type',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book/Book Chapter'), ('patent', 'Patent'), ('copyright', 'Copyright'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
