# Generated by Django 5.1.1 on 2025-05-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0011_alter_filloutfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filloutform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to='flexapp.faculty'),
        ),
    ]
