# Generated by Django 5.1.1 on 2025-05-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0012_alter_filloutform_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_view_certificates', models.BooleanField(default=False)),
                ('can_view_publications', models.BooleanField(default=False)),
                ('can_view_projects', models.BooleanField(default=False)),
                ('faculties', models.ManyToManyField(related_name='coordinator_roles', to='flexapp.faculty')),
                ('providers', models.ManyToManyField(blank=True, to='flexapp.provider')),
            ],
        ),
    ]
