# Generated by Django 5.1.1 on 2025-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0013_provider_coordinatorrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='filloutfield',
            name='related_model',
            field=models.CharField(blank=True, help_text="Model name (e.g., 'certificate', 'project')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recognition',
            field=models.CharField(blank=True, choices=[('participation', 'Participation'), ('appreciation', 'Appreciation'), ('recommendation', 'Recommendation'), ('completion', 'Completion'), ('recognition', 'Recognition'), ('rankcard', 'Rankcard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='filloutfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Multiple Choice'), ('file_awk', 'Pick from your own instances or upload file')], max_length=20),
        ),
    ]
