# Generated by Django 5.1.1 on 2025-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0014_filloutfield_related_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
