# Generated by Django 5.1.1 on 2025-08-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flexapp", "0015_alter_projects_github_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_placed", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_status",
                        to="flexapp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacementOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("package", models.DecimalField(decimal_places=2, max_digits=8)),
                ("offer_date", models.DateField(blank=True, null=True)),
                ("placement_year", models.IntegerField(blank=True, null=True)),
                (
                    "placement_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of placement (e.g., Internship, Full-time)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student accepted this offer",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_offers",
                        to="flexapp.student",
                    ),
                ),
            ],
        ),
    ]
