# Generated by Django 5.1.1 on 2025-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0016_placement_placementoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorrole',
            name='can_view_placement',
            field=models.BooleanField(default=False),
        ),
    ]
