from django.urls import path
from . import views
from .views import upload_students, search_students

urlpatterns = [
    path('',views.index,name="index"),
    path('login',views.CustomLogin,name="login"),
    path('logout', views.CustomLogout, name="logout"),
    path('dashboard', views.dashboard, name="dashboard"),
    # path('updateLeet/<int:count>',views.UpdateLeet, name="updateLeet"),
    # path('register', views.register, name="register"),
    path('create-project', views.create_project, name="create_project"),
    path('add-certification', views.add_certification, name="add_certification"), 
    path('faculty', views.faculty, name="faculty"),
    path('coordinator/dashboard/', views.coordinator_dashboard, name='coordinator_dashboard'),
    path('student/<str:rollno>', views.studentView, name="studentView"),
    path('edit_project', views.edit_project, name="edit_project"),
    path('delete_project/<int:primary_key>', views.delete_project,name="delete_project"),
    path('delete_certification/<int:primary_key>', views.delete_certification, name="delete_certification"),
    path('edit_certification', views.edit_certification, name="edit_certification"),
    path('leetcode/<str:leetcode_user>', views.leetcode_request, name="leetcode"),
    path('download', views.download_request, name="download"),
    path('verify_otp', views.verify_otp, name="verify_otp"),
    path('forgot_password/verify', views.verify_otp_forgot, name="verify_otp_forgot"),
    path('forgot_password', views.forgot_password, name="forgot_password"),
    path('reset_password', views.reset_password, name="reset_password"),
    path('profile', views.student_profile, name='profile'),
    path('upload_students/', upload_students, name='upload_students'),
    path("search_students/", search_students, name="search_students"),
    path("search_technologies/", views.search_technologies, name="search_technologies"),
    path('dashboard/placement/', views.placement_dashboard, name='placement_dashboard'),
    path('fillout',views.fillout,name="fillout"),
    path("create/", views.create_form, name="create_form"),
    path("assigned/", views.list_assigned_forms, name="list_assigned_forms"),
    path("fill/<int:form_id>/", views.get_form, name="fill_form_detail"),
    path('forms/', views.form_list_view, name='form_list'),
    path('forms/<int:form_id>/', views.form_detail_view, name='form_detail'),
    path('forms/<int:form_id>/download/<str:download_type>/', views.download_csv, name='download_csv'),
    path('certificateForm', views.certificate_create, name='certificate_create'),
    path("api/student-models/<str:model_name>/", views.student_model_instances)
]
